name: 'Gets release command for ply-cli'
description: 'Greet someone and record the time'
inputs:
    files: # files is the id of the input
        description: 'Changed files'
        required: true
        default: '/fake-app-integrations/calendly/auth.js' # In what scenario will this be received by the action ? explicitly {required: false} ?
outputs:
    release: # release is the id of the output
        description: 'The release cmd to run in the next step'
runs:
    using: 'node16'
    main: 'index.js'
