on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main
            - dev

jobs:
    hello_world_job:
        runs-on: ubuntu-latest
        name: A job to say hello
        steps:
            # To use this repository's private action,
            # you must check out the repository
            - name: Checkout
              uses: actions/checkout@v3
              # this could be subbed if wanted with:
              # GabbyPly/ci-cd-testing@v1.2
              # Should be un-commented when pushing to github
            - id: files
            - name: Get changed files as json
              uses: jitterbit/get-changed-files@v1
              with:
                  format: 'json'
            - name: Get release cmd action
              uses: ./ # Uses an action in the root directory
              id: cmd
              with:
                  files: ${{ steps.files.outputs.all }} # maybe only one {} ?
            # Use the output from the `cmd` step
            - name: Get the command to run
              run: ${{ steps.cmd.outputs.release }} # Counting on the cmd step to output a value under the 'release' command
