on:
    push:
        branches:
            - main

jobs:
    release_changed_integrations:
        runs-on: ubuntu-latest
        name: Release workspaces with changed files
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              # this could be subbed if wanted with:
              # GabbyPly/ci-cd-testing@v1.2
            - name: Get changed files as json
              id: files
              uses: jitterbit/get-changed-files@v1
              with:
                  format: 'json'
            - name: Get release cmd action
              uses: ./ # Uses an action in the root directory
              id: cmd
              with:
                  files: ${{ steps.files.outputs.all }}
            # Use the output from the `cmd` step
            - name: Get the command to run
              run: ${{ steps.cmd.outputs.release }} # Counting on the cmd step to output a value under the 'release' command
