name: Release integration

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main
jobs:
    release_when_files_changed:
        runs-on: ubuntu-latest
        name: Release integrations that files were changed in
        steps:
            - name: Check out repo
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - id: files
              name: HeyMateski
              uses: jitterbit/get-changed-files@v1
              with:
                  format: 'json'
            - run: |
                  for changed_file in ${{ steps.files.outputs.all }}; do
                    echo "Do something with this ${changed_file}."
                  done
            - name: node action
              id: nodejs
              uses: ./folder
              with:
                  changed_files: ${steps.files.outputs.all}
                  changed_files_two: ${{  steps.files.outputs.all  }}
